### ISSUE TITLE
OLLVM-tll/Armariris deobfuscation sample

### ISSUE THREAD

**Issue by enovella** [obpo-project/obpo-plugin#1]
sample: https://github.com/OWASP/owasp-mstg/blob/master/Crackmes/Android/Level_04/r2pay-v1.0.apk

```sh
Traceback (most recent call last):
  File "/home/edu/idapro-7.7/plugins/obpoplugin/popup.py", line 17, in activate
    self.f(ctx)
  File "/home/edu/idapro-7.7/plugins/obpoplugin/popup.py", line 70, in mark_and_process
    process(_)
  File "/home/edu/idapro-7.7/plugins/obpoplugin/popup.py", line 30, in process
    mba = generate_microcode(func, level=LEVEL)
  File "/home/edu/idapro-7.7/plugins/obpoplugin/process.py", line 21, in generate_microcode
    raise Exception("{} generate mc error:  {}".format(hex(function.start_ea) % hf.errea, hf.str))
TypeError: not all arguments converted during string formatting
```

```sh
Traceback (most recent call last):
  File "/home/edu/idapro-7.7/plugins/obpoplugin/popup.py", line 17, in activate
    self.f(ctx)
  File "/home/edu/idapro-7.7/plugins/obpoplugin/popup.py", line 70, in mark_and_process
    process(_)
  File "/home/edu/idapro-7.7/plugins/obpoplugin/popup.py", line 33, in process
    optimized = request_process(mba, mark_manager_instance().func_marked(ea))
  File "/home/edu/idapro-7.7/plugins/obpoplugin/process.py", line 170, in request_process
    response = response.json()
  File "/home/edu/.local/lib/python3.6/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by hluwa** [comment]
Hi, I'm tested armeabi-v7a/libnative-lib.so:JNI_OnLoad function is can succeed unflattterning.

Traceback 1 is a bug for local plugins, cause by cannot generate microcode. I guess you're using outdated code. Please pull the latest code and try again, it fixed some case for generate microcode.

In addition I hope you can pr the failed samples to [obpo-project/sample](https://github.com/obpo-project/samples), and comment the function address.

**Comment by hluwa** [comment]
Traceback 2 is because my timeout was incorrectly configured as 15s. Sorry has now been restored to 60s.

**Comment by hluwa** [comment]
Binary: armeabi-v7a/libnative-lib.so
Function: sub_9C638
Marked Dispatchers: 0x9c688, 0x9d076

set x_n/y_n to const to deobfuscate bcf + obpo process:
 
```c
int __fastcall sub_9C638(_DWORD *a1, char *a2, unsigned int a3)
{
  // [COLLAPSED LOCAL DECLARATIONS. PRESS KEYPAD CTRL-"+" TO EXPAND]

  v10 = a3;
  if ( !a1 || !*a1 || !a1[2] )
    return -20736;
  if ( a3 <= *(unsigned __int8 *)(*a1 + 9) )
  {
    v8 = a1[2];
    v7 = (_BYTE *)(v8 + *(unsigned __int8 *)(*a1 + 9));
    *v14 = 54;
    v16 = *(unsigned __int8 *)(*a1 + 9);
  }
  else
  {
    v9 = sub_9B320(a1);
    if ( v9 || (v9 = sub_9B730(a1, a2, v10)) != 0 || (v9 = sub_9BD24(a1, v17)) != 0 )
    {
LABEL_34:
      sub_A2448(v17, 32);
      return v9;
    }
    v10 = *(unsigned __int8 *)(*a1 + 8);
    a2 = v17;
    v8 = a1[2];
    v7 = (_BYTE *)(v8 + *(unsigned __int8 *)(*a1 + 9));
    *v14 = 54;
    v16 = *(unsigned __int8 *)(*a1 + 9);
  }
  if ( v7 )
  {
    for ( i = v7; v16--; ++i )
    {
      v4 = i;
      *v4 = 92;
    }
  }
  for ( j = 0; j < v10; ++j )
  {
    *(_BYTE *)(v8 + j) = (*(_BYTE *)(v8 + j) & 9 | ~*(_BYTE *)(v8 + j) & 0xF6) ^ (a2[j] & 9 | ~a2[j] & 0xF6);
    v7[j] = v7[j] & ~a2[j] | a2[j] & ~v7[j];
  }
  v9 = sub_9B320(a1);
  if ( !v9 )
    v9 = sub_9B730(a1, v8, *(unsigned __int8 *)(*a1 + 9));
  goto LABEL_34;
}
```
